apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ci

commonAnnotations:
  package.vfeld.net/name: registry
  package.vfeld.net/version: "2"

resources:
- docker-auth-config.yaml
- docker-auth-deployment.yaml
- docker-auth-service.yaml
- registry-pod.yaml
- registry-service.yaml
#- daemon-config.yaml 
