apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ci

commonAnnotations:
  package.vfeld.net/name: registry
  package.vfeld.net/version: "2"

resources:
- ext-auth-sealed-secret.yaml
- docker-auth-config.yaml
- docker-auth-deployment.yaml
- docker-auth-service.yaml
- registry-deployment.yaml
- registry-service.yaml
- docker-auth-ingress-tls.yaml
- registry-ingress-tls.yaml
- registry-pull-seal-secret.yaml
