apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  package.vfeld.net/name: registry
  package.vfeld.net/version: 2

resources:
- pod.yaml
- service.yaml
- daemon-config.yaml 
