apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ci

commonAnnotations:
  bundle.vfeld.net/name: ci
  bundle.vfeld.net/version: 0.1.0

bases:
- ../../packages/dind-19.03
- ../../packages/pipelines-0.1.0
- ../../packages/registry-2

resources:
- ci-ingress-tls.yaml
- ci-certificate-authority.yaml
