apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

images:
- name: argoproj/argocd:v1.8.7
  newName: vfeld/argocd
  newTag: v1.8.7-kustomize-4.0.5

resources:
- namespace.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/v1.8.7/manifests/install.yaml 
