apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  package.vfeld.net/name: tekton
  package.vfeld.net/version: 0.22.0
resources:
  - 002_ClusterRole_tekton-pipelines-controller-cluster-access.yaml
  - 003_ClusterRole_tekton-pipelines-controller-tenant-access.yaml
  - 004_ClusterRole_tekton-pipelines-webhook-cluster-access.yaml
  - 030_ClusterRole_tekton-aggregate-edit.yaml
  - 031_ClusterRole_tekton-aggregate-view.yaml
  