apiVersion: v1
kind: Pod
metadata:
  name: registry
  labels:
    app: registry
spec:
  containers:
    - image: {{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
      name: registry
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 5000
      volumeMounts:
      - name: registry-vol
        mountPath: /var/lib/registry
  volumes:
  - name: registry-vol
    emptyDir: {}
