apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  package.vfeld.net/name: cert-manager
  package.vfeld.net/version: 1.3.0
resources:
  - 000_CustomResourceDefinition_certificaterequests.cert-manager.io.yaml
  - 001_CustomResourceDefinition_certificates.cert-manager.io.yaml
  - 002_CustomResourceDefinition_challenges.acme.cert-manager.io.yaml
  - 003_CustomResourceDefinition_clusterissuers.cert-manager.io.yaml
  - 004_CustomResourceDefinition_issuers.cert-manager.io.yaml
  - 005_CustomResourceDefinition_orders.acme.cert-manager.io.yaml
  