apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  package.vfeld.net/name: cert-manager
  package.vfeld.net/version: 1.3.0
resources:
  - 021_ClusterRoleBinding_cert-manager-cainjector.yaml
  - 022_ClusterRoleBinding_cert-manager-controller-issuers.yaml
  - 023_ClusterRoleBinding_cert-manager-controller-clusterissuers.yaml
  - 024_ClusterRoleBinding_cert-manager-controller-certificates.yaml
  - 025_ClusterRoleBinding_cert-manager-controller-orders.yaml
  - 026_ClusterRoleBinding_cert-manager-controller-challenges.yaml
  - 027_ClusterRoleBinding_cert-manager-controller-ingress-shim.yaml
  - 028_ClusterRoleBinding_cert-manager-controller-approve:cert-manager-io.yaml
  - 029_ClusterRoleBinding_cert-manager-webhook:subjectaccessreviews.yaml
  