apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  package.vfeld.net/name: sealed-secrets
  package.vfeld.net/version: 0.15.0
resources:
  - 006_ClusterRoleBinding_sealed-secrets-controller.yaml
  