apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ci-dind
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/vfeld/schocken-infrastructure.git
    targetRevision: HEAD
    path: packages/dind-19.03
  destination:
    server: https://kubernetes.default.svc
    namespace: ci
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
