apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  package.vfeld.net/name: tekton-triggers
  package.vfeld.net/version: 0.12.1
resources:
  - 009_ClusterRoleBinding_tekton-triggers-controller-admin.yaml
  - 010_ClusterRoleBinding_tekton-triggers-webhook-admin.yaml
  - 011_ClusterRoleBinding_tekton-triggers-core-interceptors.yaml
  