apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  name: build-sh-run
  namespace: ci
spec:
  taskRef:
    name: build-sh
  serviceAccountName: ci-admin
  workspaces:
  - name: source
    emptyDir: {}
