apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  package.vfeld.net/name: cert-manager
  package.vfeld.net/version: 1.3.0
resources:
  - 010_ClusterRole_cert-manager-cainjector.yaml
  - 011_ClusterRole_cert-manager-controller-issuers.yaml
  - 012_ClusterRole_cert-manager-controller-clusterissuers.yaml
  - 013_ClusterRole_cert-manager-controller-certificates.yaml
  - 014_ClusterRole_cert-manager-controller-orders.yaml
  - 015_ClusterRole_cert-manager-controller-challenges.yaml
  - 016_ClusterRole_cert-manager-controller-ingress-shim.yaml
  - 017_ClusterRole_cert-manager-view.yaml
  - 018_ClusterRole_cert-manager-edit.yaml
  - 019_ClusterRole_cert-manager-controller-approve:cert-manager-io.yaml
  - 020_ClusterRole_cert-manager-webhook:subjectaccessreviews.yaml
  