apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  bundles.vfeld.net/name: ci-sealed-secret
  bundles.vfeld.net/version: 0.1.0

bases:
- ../../packages/sealed-secrets-0.15.0/crd
- ../../packages/sealed-secrets-0.15.0/cr
- ../../packages/sealed-secrets-0.15.0/crb
- ../../packages/sealed-secrets-0.15.0/main
