apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: fetch-build
spec:
  description: |
    fetch and build takes a git repository, git revision and
    a docker dockerfile and context and builds an image.
  params:
  - name: repo-url
    type: string
    description: The git repository URL to clone from.
  - name: git-rev
    type: string
    description: The git rev to clone, e.g. branch name, tag, ...
  - name: dockerfile 
    description: Path to the Dockerfile to build. 
    default: ./Dockerfile 
  - name: context 
    description: Path to the directory to use as docker context. 
    default: . 
  - name: build_extra_args 
    description: Extra parameters passed for the docker build command when building images. 
    default: ""
  - name: destination-image 
    description: Reference of the image docker will produce. 
  workspaces:
  - name: shared-data
    description: |
      This workspace will receive the cloned git repo and be passed
      to the next Task for the repo's README.md file to be read.
  tasks:
  - name: fetch-repo
    taskRef:
      name: git-clone
    workspaces:
    - name: output
      workspace: shared-data
    params:
    - name: url
      value: $(params.repo-url)
    - name: revision
      value: $(params.git-rev)
  - name: build-image
    runAfter: ["fetch-repo"]
    taskRef:
      name: dind-build
    workspaces:
    - name: source
      workspace: shared-data
    params: 
    - name: image 
      value: $(params.destination-image)
    - name: dockerfile 
      value: $(params.dockerfile)
    - name: context 
      value: $(params.context)
    - name: build_extra_args 
      value: $(params.build_extra_args)
