---
apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: github-listener-interceptor
spec:
  triggers:
    - name: github-listener
      interceptors:
        - github:
            secretRef:
              secretName: github-secret
              secretKey: secretToken
            eventTypes:
              - push
      bindings:
        - ref: fetch-build-binding
      template:
        ref: fetch-build-trigger-template
  resources:
    kubernetesResource:
      spec:
        template:
          spec:
            serviceAccountName: tekton-triggers-sa
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerBinding
metadata:
  name: fetch-build-binding
spec:
  params:
    - name: git-rev
      value: $(body.head_commit.id)
    - name: git-clone-url
      value: $(body.repository.clone_url)
    - name: git-repo-name
      value: $(body.repository.name)
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: fetch-build-trigger-template
spec:
  params:
    - name: git-clone-url
    - name: git-repo-name
    - name: git-rev
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      generateName: fetch-build-
    spec:
      pipelineRef:
        name: fetch-build
      serviceAccountName: ci
      workspaces:
      - name: shared-data
        volumeClaimTemplate:
          spec:
            accessModes:
            - ReadWriteOnce
            storageClassName: linode-block-storage
            resources:
              requests:
                storage: 10Gi
      params:
      - name: repo-url
        value: $(tt.params.git-clone-url)
      - name: git-rev
        value: $(tt.params.git-rev)
      - name: base-name
        value: $(tt.params.git-repo-name)
      - name: dockerfile 
        value: integrations/docker/Dockerfile
      - name: context 
        value: . 
