apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  package.vfeld.net/name: pipelines
  package.vfeld.net/version: "0.1.0"

resources:
- dind-build-task.yaml
- git-clone-task.yaml 
- fetch-build-pipeline.yaml
