apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  package.vfeld.net/name: pipelines
  package.vfeld.net/version: "0.1.0"

resources:
- dind-build-task.yaml
- git-clone-task.yaml 
- fetch-build-pipeline.yaml
- build-sh-task.yaml
- ci-admin-service-account.yaml
- helm-task.yaml
- ci-admin-role-binding.yaml
- trigger-service-account-roles.yaml
- fetch-build-pipeline-event-trigger.yaml
- trigger-sealed-secret.yaml


