apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  bundles.vfeld.net/name: ci-tekton
  bundles.vfeld.net/version: 0.1.0

bases:
- ../../packages/tekton-0.22.0/crd
- ../../packages/tekton-0.22.0/cr
- ../../packages/tekton-0.22.0/crb
- overlays/tekton-main
- ../../packages/tekton-dashboard-0.15.0/crd
- ../../packages/tekton-dashboard-0.15.0/cr
- ../../packages/tekton-dashboard-0.15.0/crb
- ../../packages/tekton-dashboard-0.15.0/main
- ../../packages/tekton-triggers-0.12.1/crd
- ../../packages/tekton-triggers-0.12.1/cr
- ../../packages/tekton-triggers-0.12.1/crb
- ../../packages/tekton-triggers-0.12.1/main
